baseURL: 'https://ubuntu-id.org'
languageCode: id-id
title: 'Komunitas Ubuntu Indonesia'
theme: "ubuntukr"
buildFuture: true
googleAnalytics: ""
params:
  contact: contact@ubuntu-id.org
  facebook: ubuntuindonesia
  twitter: ubuntu_id
  github: ubuntu-id
  launchpad: ubuntu-id
  telegram: https://t.me/ubuntu_id
  youtube: https://www.youtube.com/user/ubuntuindonesia
  source_repo: https://github.com/ubuntu-id/ubuntu-id.github.io
defaultContentLanguage: id
languages:
  id:
    languageName: Bahasa
    title: Komunitas Ubuntu Indonesia
    weight: 2
    params:
      description: >-
        Komunitas Ubuntu Indonesia adalah Ubuntu LoCo (Local Community) di Indonesia.
        Ini adalah tempat untuk semua orang yang tertarik menggunakan, mengembangkan, dan berkontribusi pada proyek Ubuntu.
      copyright: >-
        ©2023 Komunitas Ubuntu Indonesia (Ubuntu Indonesian LoCo Team).
        Kecuali dinyatakan lain, Kode sumber situs web dilisensikan di bawah MIT, Konten dilisensikan di bawah CC BY-SA 4.0.
        Ubuntu dan Canonical adalah merek dagang terdaftar dari Canonical Ltd.
      main_slide:
        label: Tentang Komunitas
        link: about
    menu:
      main:
      - identifier: try
        name: Coba Ubuntu
        weight: 1
      - identifier: download
        parent: try
        name: Unduh
        url: download
        weight: 11
      - identifier: hardware
        name: Perangkat Keras Bersertifikat Ubuntu
        parent: try
        url: https://ubuntu.com/certified
        weight: 12
      - identifier: docs-en
        parent: try
        name: Dokumentasi
        url: https://docs.ubuntu.com
        weight: 13
      - identifier: tutorials-en
        parent: try
        name: Tutorial
        url: https://ubuntu.com/tutorials
        weight: 14
      - identifier: wiki-en
        parent: try
        name: Wiki
        url: https://wiki.ubuntu.com
        weight: 15
      - identifier: about-group
        name: Tentang
        weight: 2
      - identifier: about
        parent: about-group
        name: Tentang Komunitas
        url: about
        weight: 21
      - identifier: bylaws
        parent: about-group
        name: Legal
        url: bylaws
        weight: 22
      - identifier: sponsors
        parent: about-group
        name: Sponsor
        url: sponsors
        weight: 23
      - identifier: community
        name: Komunitas
        url: community
        weight: 3
      - identifier: forum
        parent: community
        name: Forum
        url: https://forum.ubuntu-id.org
        weight: 32
      - identifier: telegram-group
        parent: community
        name: Grup Telegram
        url: https://t.me/ubuntu_indo
        weight: 33
      - identifier: fb-group
        parent: community
        name: Grup Facebook
        url: https://www.facebook.com/groups/2327054593
        weight: 34
      - identifier: lists
        parent: community
        name: Mailing list
        url: http://groups.google.com/group/id-ubuntu
        weight: 35
        #- identifier: chat
        #parent: community
        #name: Chat 
        #url: chat
        #weight: 36
      - identifier: partandcontrib
        name: Ikut Berkontribusi
        url: partandcontrib
        weight: 4
      - identifier: events
        parent: partandcontrib
        name: Acara
        url: https://events.ubuntu-id.org
        weight: 41
      - identifier: study_projects
        parent: partandcontrib
        name: Kelompok Belajar/Proyek
        url: projects
        weight: 42
      - identifier: translate
        parent: partandcontrib
        name: Terjemahkan Ubuntu
        url: translate
        weight: 43
      - identifier: follow
        name: Ikuti Kami
        weight: 5
      - identifier: blog
        parent: follow
        name: Blog
        url: http://ubuntulinux.or.id
        weight: 51
      - identifier: facebook
        parent: follow
        name: Facebook
        url: https://facebook.com/ubuntu.indonesia
        weight: 52
      - identifier: twitter
        parent: follow
        name: Twitter
        url: https://twitter.com/ubuntu_id
        weight: 53
      - identifier: youtube
        parent: follow
        name: YouTube
        url: https://www.youtube.com/user/ubuntuindonesia
        weight: 54
      - identifier: telegram
        parent: follow
        name: Saluran Telegram
        url: https://t.me/ubuntu_id
        weight: 55
  en:
    languageName: English
    title: Ubuntu Indonesia Community
    weight: 2
    params:
      description: >-
        Ubuntu Indonesia Community is a Ubuntu LoCo (Local Community) in Indonesia.
        It is a place for everyone who intrested in using, developing with ubuntu, or contributing to ubuntu projects.
      copyright: >-
        ©2022 Ubuntu Indonesia Community (Ubuntu Indonesian LoCo Team).
        Except where otherwise noted, Website source code licensed under MIT, Contents licensed under CC BY-SA 4.0. 
        Ubuntu and Canonical are registered trademarks of Canonical Ltd.
      main_slide:
        label: About the community
        link: about
    menu:
      main:
      - identifier: try
        name: Try Ubuntu
        weight: 1
      - identifier: download
        parent: try
        name: Download
        url: download
        weight: 11
      - identifier: hardware
        name: Ubuntu Certified Hardwares
        parent: try
        url: https://ubuntu.com/certified
        weight: 12
      - identifier: docs-en
        parent: try
        name: Docs
        url: https://docs.ubuntu.com
        weight: 13
      - identifier: tutorials-en
        parent: try
        name: Tutorials
        url: https://ubuntu.com/tutorials
        weight: 14
      - identifier: wiki-en
        parent: try
        name: Wiki
        url: https://wiki.ubuntu.com
        weight: 15
      - identifier: about-group
        name: About
        weight: 2
      - identifier: about
        parent: about-group
        name: About our community
        url: about
        weight: 21
      - identifier: bylaws
        parent: about-group
        name: Legal
        url: bylaws
        weight: 22
      - identifier: sponsors
        parent: about-group
        name: Sponsors
        url: sponsors
        weight: 23
      - identifier: community
        name: Community
        url: community
        weight: 3
      - identifier: forum
        parent: community
        name: Forum
        url: https://forum.ubuntu-id.org
        weight: 32
      - identifier: telegram-group
        parent: community
        name: Telegram Group
        url: https://t.me/ubuntu_indo
        weight: 33
      - identifier: fb-group
        parent: community
        name: Facebook Group
        url: https://www.facebook.com/groups/2327054593
        weight: 34
      - identifier: lists
        parent: community
        name: Mailing list
        url: http://groups.google.com/group/id-ubuntu
        weight: 35
        #- identifier: chat
        #parent: community
        #name: Chat 
        #url: chat
        #weight: 36
      - identifier: partandcontrib
        name: Participate & Contribute
        url: partandcontrib
        weight: 4
      - identifier: events
        parent: partandcontrib
        name: Join events
        url: https://event.ubuntu-id.org
        weight: 41
      - identifier: study_projects
        parent: partandcontrib
        name: Group Studies/Projects
        url: projects
        weight: 42
      - identifier: translate
        parent: partandcontrib
        name: Translate Ubuntu
        url: translate
        weight: 43
      - identifier: follow
        name: Follow us
        weight: 5
      - identifier: blog
        parent: follow
        name: Blog
        url: http://ubuntulinux.or.id
        weight: 51
      - identifier: facebook
        parent: follow
        name: Facebook
        url: https://facebook.com/ubuntu.indonesia
        weight: 52
      - identifier: twitter
        parent: follow
        name: Twitter
        url: https://twitter.com/ubuntu_id
        weight: 53
      - identifier: youtube
        parent: follow
        name: YouTube
        url: https://www.youtube.com/user/ubuntuindonesia
        weight: 54
      - identifier: telegram
        parent: follow
        name: Telegram Channel
        url: https://t.me/ubuntu_id
        weight: 55
