# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout src repo
        uses: actions/checkout@v2
        with:
          ref: main
          path: src

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.18.1'

      - name: Install Hugo
        working-directory: src
        run: |
          wget https://github.com/gohugoio/hugo/releases/download/v0.99.1/hugo_extended_0.99.1_Linux-64bit.deb -O hugo.deb
          DEBIAN_FRONTEND=noninteractive sudo dpkg -i hugo.deb
          wget https://github.com/sass/dart-sass-embedded/releases/download/1.52.1/sass_embedded-1.52.1-linux-x64.tar.gz -O dartsass.tar.gz
          tar -xvzf dartsass.tar.gz
          sudo cp sass_embedded/dart-sass-embedded /usr/bin/

      - name: Build website with Hugo
        working-directory: src
        run: |
          hugo mod get
          cd themes/ubuntukr && npm i && cd ../../
          hugo

      - name: Checkout dest repo
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          fetch-depth: 0
          path: dest

      - name: Copy website built from src/public
        working-directory: dest
        run: |
          rm -rf *
          yes | cp -rf ../src/public/* .

      - name: Commit website updates
        working-directory: dest
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Deploy website updates with GitHub Actions: ${{ github.sha }}"
          git push origin gh-pages
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dest
